language: r
sudo: required
dist: trusty
bioc_required: true
services:
- docker
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
    - libudunits2-dev                     # units > ggforce > ggraph > patchwork > dynplot
    - libssh-dev                          # ssh > qsub
before_install:
 - cd package
git:
    submodules: false
install:
- if [ `git branch | grep '* master' | wc -l` == 0 ]; then sed -i 's#\(dynverse/[^, ]*\)#\1@devel#' DESCRIPTION; fi
- R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
- R -e 'devtools::install_cran("covr")'
- R -e 'setRepositories(ind = 1:4); devtools::install(dependencies = TRUE, upgrade = TRUE)'
after_success:
- R -e 'covr::codecov()'
